### ISSUE TITLE
hamburger menu doesn't toggle

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/mediators.ai-qa#17] opened 2022-08-10 15:04 UTC
There appears to be a small accessibility issue.

When accessing the site on a mobile (sm) device, the hamburger icon tap does not toggle the navigation to open. I'd have to tap next to the icon, but not the icon itself to trigger opening the menu.

**Comment by dsleylian** [comment] 2022-08-10 18:35
@manonthemat see correction below. fixed it with z indexing and it all seems to work now.

**Comment by dsleylian** [comment] 2022-08-10 18:42
correction: the issue is that the logo is pushed up with -mt-32 and covers the button for the drawer. trying to see if this can be resolved with z index maybe

**Closed as completed** 2022-08-10 22:49 UTC
Labels: bug
